name: TagBot
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  TagBot:
    if: github.event.issue.pull_request == null && contains(github.event.comment.body, '@JuliaRegistries TagBot')
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
